apiVersion: apps/v1
kind: Deployment
metadata:
  name: cicd
  labels: 
    app: cicd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cicd
  template:
    metadata:
      labels:
        app: cicd
    spec:
      containers:
      - name: cicd
        image: sujanmj/cicd:latest
        ports:
        - name: cicd-port
          containerPort: 8080